spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

#    properties:
#      hibernate:
#        default_schema: schema.sql
