DROP TABLE IF EXISTS emails, pet;

CREATE TABLE emails(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR2(30) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL ,
    FIO VARCHAR2(256) NOT NULL,
    birthday DATE,
    male BOOLEAN,
    pet_id BIGINT
);

CREATE TABLE pet(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    breed VARCHAR2(50) NOT NULL
);

ALTER TABLE emails ADD FOREIGN KEY (pet_id) REFERENCES pet(id);