DROP TABLE IF EXISTS emails;

CREATE TABLE emails(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR2(30) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL ,
    FIO VARCHAR2(256) NOT NULL,
    birthday DATE,
    male BOOLEAN
);